### PR TITLE
Create protocol-benchmarks.md

### PR DESCRIPTION
**Pull request by jdlewin**

### CODE REVIEW

**Comment by amark** [comment]
@gvelez17 will you merge so we can fork & PR again? I don't know how to PR on a PR. :(

**Comment by jdlewin** [comment]
Are you not able to edit in the branch this PR spun up @amark? Is there something I can do differently in the future?

**Comment by amark** [comment]
Apparently I'm not smart enough. Even though I tried using your branch, it seems like it just generated an entirely new pull and didn't combine it with this.

So I propose closing this, in favor of (I manually merged the other thread too) with this:

https://github.com/blueskyCommunity/aozora/pull/41

**Comment by gvelez17** [comment]
Got it, closed that one, you want to open a new one against master from
your new branch and we can get comments & merge it in?

**Pull request closed without merging**
